apiVersion: v1
kind: Pod
metadata:
  name: syscalltest2
spec:
  runtimeClassName: quark
  containers:
  - name: syscall
    image: yaoxinjing/syscall-test
    env:
    - name: APPLICATION_NAME
      value: "test_get_report"
    - name: SECRET_MANAGER_IP
      value: "10.206.133.76:8000"
    - name: SHILED_POLICY_PATH
      value: "quark_mongo/resource/policy"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: "200Mi"