apiVersion: v1
kind: Pod
metadata:
  name: test-file-secret
spec:
  volumes:
    - name: my-mongo-persistent-storage
      persistentVolumeClaim:
        claimName: my-mongo-pvc
    - name: my-mongo-config
      configMap:
        name: my-mongo-config
    - name: my-mongo-ssl-certs
      secret:
        secretName: my-mongo-ssl-certs
  runtimeClassName: quark
  containers:
  - name: syscall
    image:  yaoxinjing/file-base-secret-test:latest
    command: ["/usr/src/app/test_get_report_syscall"]
    args: ["1000000"]
    env:
    - name: APPLICATION_NAME
      value: "test_get_report"
    - name: SECRET_MANAGER_IP
      value: "10.221.117.198:8000"
    - name: SHILED_POLICY_PATH
      value: "quark_mongo/mongo_resource/policy"
    - name: FILE_BASED_SECRETS_PATH
      value: "quark_mongo/mongo_resource/rootCaPem"
    volumeMounts:
    - name: my-mongo-ssl-certs
      mountPath: /secret
