apiVersion: v1
kind: Pod
metadata:
  name: test-get-report-sycall1
spec:
  volumes:
    - name: sm-certificate
      secret:
        secretName: sm-certificate
  runtimeClassName: quark
  containers:
  - name: syscall
    image:  yaoxinjing/get-att-report-syscall-test:latest
    command: ["/usr/src/app/test_get_report_syscall"]
    args: ["1"]
    env:
    - name: APPLICATION_NAME
      value: "test_get_report"
    - name: SECRET_MANAGER_IP
      value: "10.221.117.198:8000"
    - name: SHILED_POLICY_PATH
      value: "quark_mongo/mongo_resource/policy"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: "200Mi"
    volumeMounts:
    - name: sm-certificate
      mountPath: /usr/local